services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
     - "RABBITMQ_DEFAULT_USER=test"
     - "RABBITMQ_DEFAULT_PASS=test"
     - "RABBITMQ_DEFAULT_VHOST='vhost'"
    restart: unless-stopped
