name: Cargo build and test

on:
  push:
    branches: [ develop, main, release/**, hotfix/** ]
  pull_request:
    branches: [ develop, main, release/**, hotfix/** ]


jobs:
  build_and_test:
    name: Build and test meshpulse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: docker compose up
        run: |
          docker compose -f docker/mqtt/docker-compose.yml up -d
      - name: cargo test
        run: |
          cd meshpulse
          cargo test

  # publish_to_crates_io:
  #   name: "Publish to crates.io"
  #   runs-on: ubuntu-latest
  #   needs: build_and_test
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push' 
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       fetch-depth: 0
  #   - name: Install GitVersion
  #     uses: gittools/actions/gitversion/setup@v0.9.7
  #     with:
  #       versionSpec: '5.x'
  #   - name: Determine Version
  #     uses: gittools/actions/gitversion/execute@v0.9.7
  #     with:
  #       useConfigFile: true
  #   - name: "Overwrite version numbers"
  #     run:  awk 'NR==1,/version = "0.1.0"/{sub(/version = "0.1.0"/, "version = \"'$GitVersion_SemVer'\"")} 1' Cargo.toml > Cargo.tmp && mv Cargo.tmp Cargo.toml
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #         toolchain: stable
  #         override: true
  #   - uses: katyo/publish-crates@v2
  #     with:
  #         registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  #         args: --allow-dirty
